name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t djez59/my-portfolio:latest .
          docker push djez59/my-portfolio:latest

      - name: Ensure .ssh directory exists
        run: mkdir -p ~/.ssh

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H 212.227.194.120 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Check file permissions
        run: ls -l ~/.ssh/

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@212.227.194.120 "docker stop portfolio-container || true && docker rm portfolio-container || true && docker pull djez59/my-portfolio:latest && docker run -d --name portfolio-container -p 3000:3000 djez59/my-portfolio:latest && docker image prune -f"